"use client";
import { useState } from "react";
import ReactMarkdown from "react-markdown";
import PremiumModal from "@/components/PremiumModal";
import { detectMood } from "@/lib/mood";

const personas=["Sahabat Hangat","Kakak Bijak","Teman Receh","Motivator"];
export default function ChatPage(){const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [premium,setPremium]=useState(false); const [messages,setMessages]=useState<{role:string;content:string;}[]>([]); const [persona,setPersona]=useState(personas[0]); const mood=detectMood(input);
const send=async()=>{if(!input.trim()) return; const user={role:"user",content:input}; setMessages(m=>[...m,user]); setInput(""); setLoading(true); const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:user.content,persona,chatId:"demo"})}); const data=await res.json(); setMessages(m=>[...m,{role:"assistant",content:data.reply}]); setLoading(false);};
return <div className="h-screen flex"><aside className="w-72 hidden md:flex flex-col border-r p-4 bg-white/80"><h2 className="font-bold text-xl">RuangTeduh</h2><button className="mt-4 rounded-xl p-2 bg-lavender text-white">+ Curhat Baru</button><div className="flex-1 mt-4 text-sm text-slate-500">Riwayat chat</div><button onClick={()=>setPremium(true)} className="rounded-xl p-2 bg-softBlue text-white">Upgrade Premium</button></aside><main className="flex-1 flex flex-col"><header className="p-4 border-b flex justify-between"><select value={persona} onChange={e=>setPersona(e.target.value)}>{personas.map(p=><option key={p}>{p}</option>)}</select><div>Mood: <span className="font-semibold">{mood}</span></div></header><section className="flex-1 overflow-y-auto p-4 space-y-3">{messages.length===0?<div><h3 className="text-2xl font-semibold">Apa yang ingin kamu ceritakan hari ini?</h3><div className="flex gap-2 mt-3 flex-wrap">{["Aku lagi overthinking","Aku butuh semangat","Aku lagi sedih","Aku ingin ngobrol santai"].map(s=><button onClick={()=>setInput(s)} className="px-3 py-2 rounded-full bg-white border" key={s}>{s}</button>)}</div></div>:messages.map((m,i)=><div key={i} className={`p-3 rounded-2xl max-w-3xl ${m.role==='user'?'bg-softBlue text-white ml-auto':'bg-white'}`}><ReactMarkdown>{m.content}</ReactMarkdown></div>)}{loading&&<p className="text-slate-500">Mengetik...</p>}</section><footer className="p-4 border-t"><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Tulis isi hati kamu di sini..." className="flex-1 p-3 rounded-xl border"/><button onClick={send} className="px-4 rounded-xl bg-softBlue text-white">Kirim</button></div></footer></main><PremiumModal open={premium} onClose={()=>setPremium(false)}/></div>}
